name: vc_safety2

channels:
  - conda-forge

dependencies:
  - python=3.11

  # Core scientific stack
  - numpy=2.4
  - pandas=3.0.1
  - matplotlib=3.10

  # Geospatial
  - geopandas=1.1.2
  - pyproj=3.7.2
  - shapely
  - fiona
  - rtree

  # Visualization
  - plotly=6.5
  - altair=6.0.0
  - vega_datasets=0.9.0
  - ipywidgets=8.1
  - ipython=9.10

  # Notebook (optional but currently included)
  - jupyterlab=4.5

  - pip
  - pip:
      - shiny==1.5.1
      - shinywidgets==0.7.1
      - folium==0.20.0
      - faicons==0.2.2